package com.cuieney.rxpay_compile

import com.squareup.javapoet.ClassName

/**
 * Created by cuieney on 2017/11/29.
 */
/**
 * save constants for generate code
 */

object Consts {
    const val ANNOTATION_TYPE_WX = "com.cuieney.rxpay_annotation.WX"
    const val WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY RXPAY."

    val IWXAPI = ClassName.get("com.tencent.mm.opensdk.openapi", "IWXAPI")
    val IWXAPI_EVENT_HANDLER = ClassName.get("com.tencent.mm.opensdk.openapi", "IWXAPIEventHandler")
    val WXPAYWAT_CN = ClassName.get("com.cuieney.sdk.rxpay.wechatpay", "WXPayWay")
    val WXAPI_CN = ClassName.get("com.tencent.mm.opensdk.openapi", "WXAPIFactory")
    val RXBUS_CN = ClassName.get("com.cuieney.sdk.rxpay", "RxBus")
    val PAYMENT_CN = ClassName.get("com.cuieney.sdk.rxpay", "PaymentStatus")
    val ACTIVITY_CN = ClassName.get("android.app", "Activity")
    val BASERESP_CN = ClassName.get("com.tencent.mm.opensdk.modelbase", "BaseResp")
    val BASEREQ_CN = ClassName.get("com.tencent.mm.opensdk.modelbase", "BaseReq")
    val INTENT_CN = ClassName.get("android.content", "Intent")
    val BUNDLE_CN = ClassName.get("android.os", "Bundle")
    val LOG_CN = ClassName.get("android.util", "Log")

}