package com.cuieney.rxpay_compile;

import com.squareup.javapoet.ClassName;

/**
 * save constants for generate code
 */

public class Consts {
    public static final String ANNOTATION_TYPE_WX = "com.cuieney.rxpay_annotation.WX";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY RXPAY.";

    public static final String IWXAPI = "com.tencent.mm.opensdk.openapi.IWXAPI";
    public static final String IWXAPIEventHandler = "com.tencent.mm.opensdk.openapi.IWXAPIEventHandler";

    public static final ClassName WXPAYWAT_CN = ClassName.get("com.cuieney.sdk.rxpay.wechatpay", "WXPayWay");
    public static final ClassName WXAPI_CN = ClassName.get("com.tencent.mm.opensdk.openapi", "WXAPIFactory");
    public static final ClassName RXBUS_CN = ClassName.get("com.cuieney.sdk.rxpay", "RxBus");
    public static final ClassName PAYMENT_CN = ClassName.get("com.cuieney.sdk.rxpay", "PaymentStatus");
    public static final ClassName ACTIVITY_CN = ClassName.get("android.app","Activity");
    public static final ClassName BASERESP_CN = ClassName.get("com.tencent.mm.opensdk.modelbase","BaseResp");
    public static final ClassName BASEREQ_CN = ClassName.get("com.tencent.mm.opensdk.modelbase","BaseReq");
    public static final ClassName INTENT_CN =  ClassName.get("android.content","Intent");
    public static final ClassName BUNDLE_CN =  ClassName.get("android.os","Bundle");


}
